export const profileText = {
  profile: 'حساب کاربری',
  edit: 'ویرایش',
  firstName: 'نام',
  registerUserInfo: 'ثبت اطلاعات کاربری',
  lastName: 'نام خانوادگی',
  nationalCode: 'شماره ملی',
  userInfo: 'اطلاعات کاربری',
  familyMembers: 'افراد تحت تکفل',
  passwordSetting: 'تنظیمات رمز عبور',
  newPassword: 'رمز عبور جدید',
  enterNewPassword: 'رمز عبور جدید را وارد کنید',
  enterReEnterNewPassword: 'تکرار رمز عبور جدید را وارد کنید',
  reEnterNewPassword: 'تکرار رمز عبور جدید',
  addresses: 'آدرس های منتخب',
  plaque: 'پلاک',
  unit: 'واحد',
  mobileNumber: 'شماره همراه',
};
