export const selectStoreTexts = {
  pageTitle: 'انتخاب فروشگاه',
  selectDeliveryAddress: 'محل تحویل سفارش خود را مشخص کنید',
  enterAddressDetail: 'لطفا جزئیات آدرس خود را وارد کنید',
  addNewAddress: 'افزودن آدرس جدید',
  newAddress: 'آدرس جدید',
  addAddress: 'افزودن آدرس',
  selectAddress: 'انتخاب آدرس',
  editAddress: ' ویرایش آدرس',
  AddressDetail: 'توضیحات آدرس',
  selectAddressSubTitle:
    'برای مشاهده نزدیک ترین فروشگاه ها، ابتدا موقعیتتان را مشخص کنید',
  selectLocations: 'مکان تحویل سفارش خود را مشخص کنید',
  saveMyLocation: 'انتخاب موقعیت',
  confirmContinue: 'تایید و ادامه',
  confirmLocationContinue: 'تأیید آدرس مکان منتخب',
  saveLocationOnMap: 'ثبت مــوقعیت روی نقـــشه',
  saveYourAddress: 'ثبت آدرس پیش فرض با موفقیت انجام شد',
  deliveryIn: ' تحویل در ',
  changeStore: 'تغییر فروشگاه',
  searchCityPlaceholder: 'جستجوی شهر',
  searchLocationPlaceholder: 'جستجوی محله، خیابان و...',
  recipientAddress: 'آدرس تحویل گیرنده *',
  addressTitle: 'عنوان آدرس: خانه، شرکت...',
  plaque: 'پلاک',
  postalCode: 'کد پستی *',
  enterPostalCode: 'کد پستی خود را وارد کنید',
  unit: 'واحد',
  enterPlaque: 'پلاک خود را وارد کنید',
  enterUnit: 'واحد خود را وارد کنید',
  title: 'عنوان آدرس',
  recipientName: 'نام تحویل گیرنده',
  recipientMobile: 'شماره موبایل',
  enterRecipientName: 'نام گیرنده را وارد کنید',
  enterRecipientMobile: 'شماره گیرنده را وارد کنید',
  imTransferee: 'تحویل گیرنده شخص دیگری است',
  deleteAddress: 'حذف آدرس',
  deleteAddressConfirm: 'آیا از حذف این آدرس مطمئن هستید؟',
  deletedTextMessage: 'آدرس مورد نظر با موفقیت حذف شد',
  deletedFailed: 'خطا در حذف آدرس',
  unSelectAddressOnMap: 'لطفا موقعیت خود را بر روی نقشه مشخص نمایید',
  editAddressOnMap: 'ویرایش موقعیت روی نقشه',
  saveMyAddress: 'تایید و ثبت آدرس',
  addNewOrEditAddress: 'آدرس مورد نظر با موفقیت ذخیره شد',
  addNewOrEditAddressFailed: 'خطا در ذخیره آدرس، لطفا مجددا تلاش نمایید',
  addNewOrEditAddressLocationFailed:
    'مشتری گرامی آدرس انتخابی شما مربوط به فروشگاه انتخابی شما نیست',
  myLocation: 'مکان‌یابی خودکار',
  submitLocation: 'ثبت موقعیت',
  chooseManually: 'انتخاب دستی',
  notFoundStore: 'موقعیت انتخابی شما، خارج از محدوده سرویس‌دهی می‌باشد!',
  topMobileDescription:
    'برای مشاهده نزدیک ترین فروشگاه ها، ابتدا موقعیتتان را مشخص کنید',
  selectOkalaBusinessStore:
    'با انتخاب این فروشگاه ، همه کالاها از سبد خرید شما حذف می شوند، آیا با این تغییر موافق هستید؟',
  chooseLocationHint:
    'ثبت موقعیت دقیق، به شما در پیدا کردن نزدیک‌ترین فروشگاه کمک می‌کند. لطفا جهت دریافت سفارش، موقعیت خود را روی نقشه انتخاب کنید.',
  blockedLocationPermissionTitle: 'عدم دسترسی به موقعیت مکانی',
  blockedLocationPermissionCaption:
    'شما دسترسی به موقعیت مکانی خود را غیرفعال کرده‌اید.',
  blockedLocationPermissionHint:
    'لطفا برای استفاده از مکان‌یابی خودکار، تنظیمات آن را در تلفن همراه و مرورگر خود فعال کنید.',
  notInStoreType: 'این فروشگاه در محدوده انتخابی شما نیست',
  reload: 'بارگذاری مجدد',
  loadingStores: 'در حال بارگذاری اطلاعات فروشگاه‌ها',
  chooseLocationOnMapError:
    'شناسایی موقعیت مکانی شما با خطا مواجه شد. لطفا دوباره تلاش کنید.',
  selectAddressGuide:
    'با حرکت بر روی نقشه یا استفاده از بخش جستجو، مکان دقیق تحویل سفارش را مشخص کنید',
  editAddressAlert:
    'برای ویرایش آدرس ابتدا موقعیت مکانی را روی نقشه تغییر دهید.',
  noAddressSelected: 'هیچ آدرسی انتخاب نشده است',
  enterAddressTitle: 'عنوان آدرس خود را وارد کنید',
  successAddAddress: 'آدرس شما با موفقیت ایجاد شد!',
  successEditAddress: 'آدرس شما با موفقیت ویرایش شد!',
  successDeleteAddress: 'آدرس شما حذف شد!',
  orderRegistration: 'سفارش دارو با نسخه',
};
