version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.staging
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/app