version: '3'

services:
  front-end:
    image: tapsi-doctor  # Replace with your actual image name if needed.         # Start a shell.
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_MODE: staging  # Set the environment mode here.
    ports:
      - "5000:3000"       # Map port 5000 on host to port 3000 in container.
    environment:
      - NODE_ENV=production
      - PORT=3000
    # volumes:
      # - .:/app
