# production : Build
FROM tapsidoctorprod-1.0.9 AS builder

WORKDIR /app

COPY package.json ./

RUN npm install --force

COPY . .

COPY .env.production .env

RUN rm -f .env.*

RUN npm run build

FROM tapsidoctorprod-1.0.9

WORKDIR /app

COPY --from=builder /app ./

ENV PORT 3000

EXPOSE $PORT

CMD ["sh", "-c", "npm run start"]