const baseUrl = '/app';
export const routeList = {
  vmsRoute: `https://vms.tapsi.doctor`,
  landingRoute: `/`,
  homeRoute: `${baseUrl}/`,
  loginRoute: `${baseUrl}/auth`,
  logoutRoute: `${baseUrl}/logout`,
  checkoutRoute: `${baseUrl}/checkout`,
  prescriptionRegisteration: `${baseUrl}/prescription-registeration`,
  profile: `${baseUrl}/profile`,
  profileUserInfoRoute: `${baseUrl}/profile/user-info`,
  profileAddresses: `${baseUrl}/profile/addresses`,
  profileFamilyMembers: `${baseUrl}/profile/family-members`,
  profilePasswordSetting: `${baseUrl}/profile/password-setting`,
  ordersHistory: `${baseUrl}/orders-history`,
  successOrder: `${baseUrl}/success-order`,
  orderDetail: `${baseUrl}/order-detail`,
  mobileSearch: `${baseUrl}/mobileSearch`,
  search: `${baseUrl}/search`,
  offer: `${baseUrl}/offer`,
  category: `${baseUrl}/category`,
  searchByImage: `${baseUrl}/searchByImage`,
  basket: `${baseUrl}/basket`,
  tender: `${baseUrl}/tender`,
  categories: `${baseUrl}/categories`,
  otcMedicine: `${baseUrl}/otc-medicine`,
  productPage: `${baseUrl}/product/`,
  newAddress: `${baseUrl}/profile/addresses/new`,
  QuickOrder: `${baseUrl}/quick-order`,
  QuickOrderSuccess: `${baseUrl}/quick-order/success`,
  QuickOrderDetail: `${baseUrl}/quick-order/detail`,
};
