export const routeList = {
  vmsRoute: 'https://vms.tapsi.doctor',
  landingRoute: '/',
  homeRoute: '/app/',
  loginRoute: '/app/auth',
  logoutRoute: '/app/logout',
  checkoutRoute: '/app/checkout',
  prescriptionRegisteration: '/app/prescription-registeration',
  profile: '/app/profile',
  profileUserInfoRoute: '/app/profile/user-info',
  profileAddresses: '/app/profile/addresses',
  profileFamilyMembers: '/app/profile/family-members',
  profilePasswordSetting: '/app/profile/password-setting',
  ordersHistory: '/app/orders-history',
  successOrder: '/app/success-order',
  orderDetail: '/app/order-detail',
  mobileSearch: '/app/mobileSearch',
  search: '/app/search',
  category: '/app/category',
  searchByImage: '/app/searchByImage',
  basket: '/app/basket',
  pharmacies: '/app/pharmacies',
};
