export const generalTexts = {
  error: 'خطایی رخ داده است',
  IRealized: 'متوجه شدم',
  logout: 'خروج',
  confirm: 'تــاییـد',
  add: 'اضافه کردن',
  register: 'ثبت',
  cancel: 'انصراف',
  phoneNumber: 'شماره موبایل',
  pharmacy: 'داروخانه',
  drugSearch: 'جستـجوی دارو',
  yes: 'بله',
  no: 'خیر',
  viewAll: 'مشاهده همه',
  sendTo: 'ارسال به',
};
