export const orderText = {
  referenceNumber: 'شماره رهگیری',
  enterReferenceNumber: 'شماره رهگیری را وارد کنید',
  enterDoctorName: 'نام پزشک را وارد کنید',
  insuranceType: 'نوع بیمه',
  doctorName: 'نام پزشک',
  description: 'توضیحات',
  selectInsuranceType: 'نوع بیمه را وارد کنید',
  orderConfirmationQuestion: 'آیا از ثبت سفارش با اطلاعات زیر اطمینان دارید؟',
  orderCancelConfirmationQuestion: 'آیا از لغو سفارش {orderCode} اطمینان دارید؟',
  orderCancelation: 'لغو سفارش',
  familyMembers: 'افراد تحت تکفل',
  failurePaymentText: 'پرداخت شما با خطا مواجه شد',
  successPaymentText: 'پرداخت شما با موفقیت انجام شد',
};
