export const orderText = {
  referenceNumber: 'کد رهگیری نسخه',
  enterReferenceNumber: 'شماره رهگیری را وارد کنید',
  phoneNumber: 'شماره تماس',
  nationalCode: 'کد ملی',
  enterPhoneNumber: 'شماره تماس را وارد کنید',
  enterDoctorName: 'نام پزشک را وارد کنید',
  insuranceType: 'نوع بیمه خود را مشخص کنید',
  insurancePlaceholder: 'نام بیمه',
  additionalInsuranceType: 'نوع بیمه تکمیلی خود را مشخص کنید',
  doctorName: 'نام پزشک',
  description: 'توضیحات',
  reasonCancelationOrder: 'دلیل لغو سفارش',
  selectInsuranceType: 'نوع بیمه را وارد کنید',
  orderConfirmationQuestion: 'آیا از ثبت سفارش با اطلاعات زیر اطمینان دارید؟',
  orderCancelConfirmationQuestion:
    'آیا از لغو سفارش {orderCode} اطمینان دارید؟',
  orderCancelation: 'لغو سفارش',
  familyMembers: 'افراد تحت تکفل',
  failurePaymentText: 'مشکل در پرداخت',
  failurePaymentHelperText: 'برای اطلاعات بیشتر با پشتیبانی تماس بگیرید',
  successPaymentText: 'پرداخت شما با موفقیت انجام شد',
  selectDrugStore: 'داروخانه را انتخاب کنید',
  drugStorePlaceholder: 'نام داروخانه',
};
