export const profileText = {
    profile: 'حساب کاربری',
    edit: 'ویرایش',
    firstName: "نام",
    lastName: "نام خانوادگی",
    nationalCode: "شماره ملی",
    userInfo: 'اطلاعات کاربری',
    passwordSetting: 'تنظیمات رمز عبور',
    newPassword: 'رمز عبور جدید',
    enterNewPassword: 'رمز عبور جدید را وارد کنید',
    enterReEnterNewPassword: 'تکرار رمز عبور جدید را وارد کنید',
    reEnterNewPassword: 'تکرار رمز عبور جدید',
    addresses: 'آدرس ها',
    plaque: 'پلاک',
    unit: 'واحد',
}